name: Build gh-pages

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:2.14.1

    steps:
      - uses: actions/checkout@v2

      - run: |
          apk --no-cache add \
              make \

          tlmgr update --self \
          tlmgr install \
              atkinson \
              fontaxes

          make \
            cookbook_rust.html \
            cookbook_rust.pdf

          mkdir -p dist
          mv cookbook_rust.html dist/index.html
          mv cookbook_rust.pdf  dist/cookbook_rust.pdf

      - name: GitHub Pages
        if: success() && github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: gh-pages
          build_dir: dist # Build directory to deploy
          jekyll: false # Allow Jekyll to build your site
          keep_history: true # Create incremental commit instead of doing push force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
