name: Build gh-pages

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix build .#pdf .#html
          mkdir -p dist
          cp result*/* dist/

      - name: GitHub Pages
        if: success() && github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: gh-pages
          build_dir: dist # Build directory to deploy
          jekyll: false # Allow Jekyll to build your site
          keep_history: true # Create incremental commit instead of doing push force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
